// Mocks generated by Mockito 5.2.0 from annotations
// in orodomop_app/test/features/news/presentasion/providers/quote_list_notifier_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:orodomop_app/common/failure.dart' as _i6;
import 'package:orodomop_app/domain/entities/quote.dart' as _i7;
import 'package:orodomop_app/domain/repositorys/quote_repository.dart' as _i2;
import 'package:orodomop_app/domain/usecases/get_quote.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeQuoteRepository_0 extends _i1.Fake implements _i2.QuoteRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetQuote].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetQuote extends _i1.Mock implements _i4.GetQuote {
  MockGetQuote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuoteRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeQuoteRepository_0()) as _i2.QuoteRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Quote>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i3.Either<_i6.Failure, List<_i7.Quote>>>.value(
              _FakeEither_1<_i6.Failure, List<_i7.Quote>>())) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i7.Quote>>>);
}
