// Mocks generated by Mockito 5.2.0 from annotations
// in orodomop_app/test/features/news/presentasion/pages/news_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:orodomop_app/common/state_enum.dart' as _i5;
import 'package:orodomop_app/domain/entities/news.dart' as _i4;
import 'package:orodomop_app/domain/usecases/get_news.dart' as _i2;
import 'package:orodomop_app/presentation/provider/news_list_notifier.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetNews_0 extends _i1.Fake implements _i2.GetNews {}

/// A class which mocks [NewsListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsListNotifier extends _i1.Mock implements _i3.NewsListNotifier {
  MockNewsListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetNews get getNews => (super.noSuchMethod(Invocation.getter(#getNews),
      returnValue: _FakeGetNews_0()) as _i2.GetNews);
  @override
  List<_i4.News> get newsList => (super
          .noSuchMethod(Invocation.getter(#newsList), returnValue: <_i4.News>[])
      as List<_i4.News>);
  @override
  _i5.RequestState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _i5.RequestState.Empty) as _i5.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i6.Future<void> fetchGetNews() =>
      (super.noSuchMethod(Invocation.method(#fetchGetNews, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void addListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
